"""Update movies table

Revision ID: ec884aff8da5
Revises: 9328bdef7634
Create Date: 2025-04-07 23:29:00.845713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec884aff8da5'
down_revision: Union[str, None] = '9328bdef7634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('movies', sa.Column('poster_path', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('genres', sa.String(), nullable=True))

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'poster_path')
    op.drop_column('movies', 'genres')
    # ### end Alembic commands ###