"""Update movies table 2

Revision ID: ef15796f3e7e
Revises: ec884aff8da5
Create Date: 2025-04-07 23:48:40.524012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef15796f3e7e'
down_revision: Union[str, None] = 'ec884aff8da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('movies', sa.Column('rating_count', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('overview', sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'overview')
    op.drop_column('movies', 'rating_count')
    # ### end Alembic commands ###
